version: "3.9"  # optional since v1.27.0
services:
  postgresSql:
    image: postgres:12.9-alpine
    environment:
      POSTGRES_DB : mfi
      POSTGRES_USER: mfi
      POSTGRES_PASSWORD: postgres 
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
      image: redis:alpine
      command: redis-server --port 6379
      container_name: redis_boot
      hostname: redis_boot
      labels:
        - "name=redis"
        - "mode=standalone"
      ports:
        - 6379:6379
        
  backend:
    build:
      context: .
      dockerfile: ./server/dockerfile
    depends_on:
      - postgresSql
    ports:
      - 3000:3000

  frontend:
    build:
      context: .
      dockerfile: ./front/dockerfile
    ports:
      - 80:80

volumes:
  db_data: